---
- name: Add Users
  hosts: default
  become: true
  tasks:
    - name: Create user accounts and add them to sudo group
      user:
        name: "{{ item | basename}}"
        groups: "sudo"
        system: no
        createhome: yes
        shell: "/bin/bash"
      with_fileglob:
        - "../ssh/*"
    - name: Add SSH access for users
      authorized_key:
        user: "{{ item | basename }}"
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../ssh/*"
    - name: Allow sudo without password for sudo group
      copy:
        content: '%sudo  ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/sudo_nopasswd
        mode: 0440

- name: Harden sshd_config
  hosts: default
  become: true
  vars:
    sshd:
      X11Forwarding: no
      UseDNS: yes
      MaxAuthTries: 3
      LoginGraceTime: 20
      AllowAgentForwarding: no
      AllowTcpForwarding: no
      PasswordAuthentication: no
      Port: 22222
  roles:
    - role: willshersystems.sshd

- name: Format and mount persistent storage
  hosts: default
  become: true
  tasks:
    - name: Format filesystem on block device
      filesystem:
        fstype: ext4
        dev: /dev/xvdb
    - name: Mount block device to /data
      mount:
       path: /data
       src: /dev/xvdb
       state: mounted
       fstype: ext4

- name: Perform system configuration
  hosts: default
  become: true
  tasks:
    - name: Create default code deployment directory
      file:
        path: /data/www
        state: directory
        mode: "0755"
        owner: "www-data"
        group: "deployer"
    - name: Create default log directory
      file:
        path: /var/log/permanent
        state: directory
        mode: "0755"
        owner: "www-data"
        group: "deployer"
    - name: Change hostname
      shell: hostnamectl set-hostname --static {{ perm_hostname }}
    - name: Preserve hostname between reboots
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: "^preserve_hostname:"
        line: "preserve_hostname: true"
    - name: Update hosts to know about the new host name
      shell: echo "127.0.0.1 {{ perm_hostname }}" >> /etc/hosts
    - name: Run the configure script
      script: "{{ script }}"
      environment:
        APP_ID: "{{ app_id }}"
        AWS_REGION: "{{ aws_region }}"
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_ACCESS_SECRET: "{{ aws_secret_access_key }}"
        PERM_ENV: "{{ perm_env }}"
        PERM_SUBDOMAIN: "{{ perm_subdomain }}"
        TEMPLATES_PATH: "{{ templates_path }}"
        NOTIFICATION_DATABASE_URL: "{{ notification_database_url }}"

        # Note the leading space: without it, Ansible will try to parse the
        # JSON data and completely mangle the string.
        # See https://github.com/ansible/ansible-modules-core/issues/2836#issuecomment-172649358
        # Even with the leading space, we still need to re-escape the newlines,
        # because Ansible is - maddeningly - parsing the contents of the string.
        NOTIFICATION_FIREBASE_CREDENTIALS: " {{ notification_firebase_credentials | replace('\n', '\\n') }}"

        UPLOAD_SERVICE_SENTRY_DSN: "{{ sentry_dsn }}"
        NEW_RELIC_LICENSE_KEY: "{{ new_relic_license_key }}"
        NEW_RELIC_APPLICATION_NAME: "{{ new_relic_application_name }}"
        APP_USER: "deployer"
        CRAWLER_REGEX: "curl|developers\\.google|(Googlebot\\/|Googlebot-Mobile|Googlebot-Image|Googlebot-News|Googlebot-Video|AdsBot-Google([^-]|$)|AdsBot-Google-Mobile|Feedfetcher-Google|Mediapartners-Google|Mediapartners \\(Googlebot\\)|APIs-Google|bingbot|Slurp|[wW]get|LinkedInBot|Python-urllib|python-requests|libwww-perl|httpunit|nutch|Go-http-client|phpcrawl|msnbot|jyxobot|FAST-WebCrawler|FAST Enterprise Crawler|BIGLOTRON|Teoma|convera|seekbot|Gigabot|Gigablast|exabot|ia_archiver|GingerCrawler|webmon |HTTrack|grub.org|UsineNouvelleCrawler|antibot|netresearchserver|speedy|fluffy|findlink|msrbot|panscient|yacybot|AISearchBot|ips-agent|tagoobot|MJ12bot|woriobot|yanga|buzzbot|mlbot|YandexBot|YandexImages|YandexAccessibilityBot|YandexMobileBot|purebot|Linguee Bot|CyberPatrol|voilabot|Baiduspider|citeseerxbot|spbot|twengabot|postrank|TurnitinBot|scribdbot|page2rss|sitebot|linkdex|Adidxbot|ezooms|dotbot|Mail.RU_Bot|discobot|heritrix|findthatfile|europarchive.org|NerdByNature.Bot|sistrix crawler|Ahrefs(Bot|SiteAudit)|fuelbot|CrunchBot|IndeedBot|mappydata|woobot|ZoominfoBot|PrivacyAwareBot|Multiviewbot|SWIMGBot|Grobbot|eright|Apercite|semanticbot|Aboundex|domaincrawler|wbsearchbot|summify|CCBot|edisterbot|seznambot|ec2linkfinder|gslfbot|aiHitBot|intelium_bot|facebookexternalhit|Yeti|RetrevoPageAnalyzer|lb-spider|Sogou|lssbot|careerbot|wotbox|wocbot|ichiro|DuckDuckBot|lssrocketcrawler|drupact|webcompanycrawler|acoonbot|openindexspider|gnam gnam spider|web-archive-net.com.bot|backlinkcrawler|coccoc|integromedb|content crawler spider|toplistbot|it2media-domain-crawler|ip-web-crawler.com|siteexplorer.info|elisabot|proximic|changedetection|arabot|WeSEE:Search|niki-bot|CrystalSemanticsBot|rogerbot|360Spider|psbot|InterfaxScanBot|CC Metadata Scaper|g00g1e.net|GrapeshotCrawler|urlappendbot|brainobot|fr-crawler|binlar|SimpleCrawler|Twitterbot|cXensebot|smtbot|bnf.fr_bot|A6-Indexer|ADmantX|Facebot|OrangeBot\\/|memorybot|AdvBot|MegaIndex|SemanticScholarBot|ltx71|nerdybot|xovibot|BUbiNG|Qwantify|archive.org_bot|Applebot|TweetmemeBot|crawler4j|findxbot|S[eE][mM]rushBot|yoozBot|lipperhey|Y!J|Domain Re-Animator Bot|AddThis|Screaming Frog SEO Spider|MetaURI|Scrapy|Livelap[bB]ot|OpenHoseBot|CapsuleChecker|collection@infegy.com|IstellaBot|DeuSu\\/|betaBot|Cliqzbot\\/|MojeekBot\\/|netEstate NE Crawler|SafeSearch microdata crawler|Gluten Free Crawler\\/|Sonic|Sysomos|Trove|deadlinkchecker|Slack-ImgProxy|Embedly|RankActiveLinkBot|iskanie|SafeDNSBot|SkypeUriPreview|Veoozbot|Slackbot|redditbot|datagnionbot|Google-Adwords-Instant|adbeat_bot|WhatsApp|contxbot|pinterest.com.bot|electricmonk|GarlikCrawler|BingPreview\\/|vebidoobot|FemtosearchBot|Yahoo Link Preview|MetaJobBot|DomainStatsBot|mindUpBot|Daum\\/|Jugendschutzprogramm-Crawler|Xenu Link Sleuth|Pcore-HTTP|moatbot|KosmioBot|pingdom|AppInsights|PhantomJS|Gowikibot|PiplBot|Discordbot|TelegramBot|Jetslide|newsharecounts|James BOT|Bark[rR]owler|TinEye|SocialRankIOBot|trendictionbot|Ocarinabot|epicbot|Primalbot|DuckDuckGo-Favicons-Bot|GnowitNewsbot|Leikibot|LinkArchiver|YaK\\/|PaperLiBot|Digg Deeper|dcrawl|Snacktory|AndersPinkBot|Fyrebot|EveryoneSocialBot|Mediatoolkitbot|Luminator-robots|ExtLinksBot|SurveyBot|NING\\/|okhttp|Nuzzel|omgili|PocketParser|YisouSpider|um-LN|ToutiaoSpider|MuckRack|Jamie's Spider|AHC\\/|NetcraftSurveyAgent|Laserlikebot|^Apache-HttpClient|AppEngine-Google|Jetty|Upflow|Thinklab|Traackr.com|Twurly|Mastodon|http_get|DnyzBot|botify|007ac9 Crawler|BehloolBot|BrandVerity|check_http|BDCbot|ZumBot|EZID|ICC-Crawler|ArchiveBot|^LCC |filterdb.iss.net\\/crawler|BLP_bbot|BomboraBot|Buck\\/|Companybook-Crawler|Genieo|magpie-crawler|MeltwaterNews|Moreover|newspaper\\/|ScoutJet|(^| )sentry\\/|StorygizeBot|UptimeRobot|OutclicksBot|seoscanners|Hatena|Google Web Preview|MauiBot|AlphaBot|SBL-BOT|IAS crawler|adscanner|Netvibes|acapbot|Baidu-YunGuanCe|bitlybot|blogmuraBot|Bot.AraTurka.com|bot-pge.chlooe.com|BoxcarBot|BTWebClient|ContextAd Bot|Digincore bot|Disqus|Feedly|Fetch\\/|Fever|Flamingo_SearchEngine|FlipboardProxy|g2reader-bot|G2 Web Services|imrbot|K7MLWCBot|Kemvibot|Landau-Media-Spider|linkapediabot|vkShare|Siteimprove.com|BLEXBot\\/|DareBoost|ZuperlistBot\\/|Miniflux\\/|Feedspot|Diffbot\\/|SEOkicks|tracemyfile|Nimbostratus-Bot|zgrab|PR-CY.RU|AdsTxtCrawler|Datafeedwatch|Zabbix|TangibleeBot|google-xrawler|axios|Amazon CloudFront|Pulsepoint|CloudFlare-AlwaysOnline|Google-Structured-Data-Testing-Tool|WordupInfoSearch|WebDataStats|HttpUrlConnection|Seekport Crawler|ZoomBot|VelenPublicWebCrawler|MoodleBot|jpg-newsbot|outbrain|W3C_Validator|Validator\\.nu|W3C-checklink|W3C-mobileOK|W3C_I18n-Checker|FeedValidator|W3C_CSS_Validator|W3C_Unicorn|Google-PhysicalWeb|Blackboard|ICBot\\/|BazQux|Twingly|Rivva|Experibot|awesomecrawler|Dataprovider.com|GroupHigh\\/|theoldreader.com|AnyEvent|Uptimebot\\.org|Nmap Scripting Engine|2ip.ru|Clickagy|Caliperbot|MBCrawler|online-webceo-bot|B2B Bot|AddSearchBot|Google Favicon|HubSpot|Chrome-Lighthouse|HeadlessChrome|CheckMarkNetwork\\/|www\\.uptime\\.com|Streamline3Bot\\/|serpstatbot\\/|MixnodeCache\\/|^curl|SimpleScraper|RSSingBot|Jooblebot|fedoraplanet|Friendica|NextCloud|Tiny Tiny RSS|RegionStuttgartBot|Bytespider|Datanyze|Google-Site-Verification|TrendsmapResolver|tweetedtimes)"
        FUSION_AUTH_HOST: "{{ fusion_auth_host }}"
        FUSION_AUTH_KEY_SFTP: "{{ fusion_auth_key_sftp }}"
        SERVER_DOMAIN: "{{ server_domain }}"
        SENTRY_DSN: "{{ sentry_dsn }}"
